jaffle_shop:
  outputs:
    dev:
      dbname: airflow
      host: localhost
      pass: admin123
      port: 5432
      schema: dbt
      threads: 1
      type: postgres
      user: admin
    pro:
      dbname: airflow
      host: postgres
      pass: admin123
      port: 5432
      schema: dbt
      threads: 1
      type: postgres
      user: admin
  target: dev
